FROM golang:1.22 AS build
WORKDIR /app
COPY . .
RUN go mod tidy && go build -o /out/collector ./cmd/collector

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /out/collector /app/collector
CMD ["/app/collector"]
